### PR TITLE
[MRG+1] Add new_uids.py, script to update datasets with new UIDs

### PR DESCRIPTION
**Pull request by scaramallion**
#### What contibution are you adding? How do we use it?
Script for updating datasets with new and consistent UIDs for Study/Series/SOP Instance UID and Frame of Reference UID. Useful when the original datasets have already been imported into a system that keeps track of datasets by their UID.

 - [x] I have added a single script or subfolder to a topic folder
 - [x] I have added some form of documentation and my contact with the contribution
 - [x] I have added a link to the contribution in the topic folder's `README.md`

### CODE REVIEW

**Review by mrbean-bremen — APPROVED** [review]
Looks good! Out of interest - why do you have to change the Frame of Reference UID?

**Comment by vsoch** [comment]
Also out of curiosity - is this something that you couldn't do with deid? https://www.github.com/pydicom/deid

**Comment by darcymason** [comment]
> Also out of curiosity - is this something that you couldn't do with deid?

@vsoch, could you point to specific code or example in deid for this?  I have had to do this kind of uid substitution quite frequently, so I see a 'standalone' kind of thing (as in this PR) to be quite useful.  But if deid can do just this piece easily, it would be good to know.

**Comment by vsoch** [comment]
Sure! I can definitely make an example. To be clear - the user wants to substitute `FrameOfReferenceUID` with something custom generated?

**Comment by vsoch** [comment]
And what dataset can I provide in my mini tutorial to test with?

**Comment by darcymason** [comment]
> To be clear - the user wants to substitute `FrameOfReferenceUID` with something custom generated?

Actually, the user wants to subsitute all UIDs, I think, although it was questioned whether FrameOfReferenceUID should be changed.  But they also need to be substituted consistently since multiple data elements can refer to the same UID.

**Comment by darcymason** [comment]
> And what dataset can I provide in my mini tutorial to test with?

Well, any in the pydicom test files could work I suppose, although should probably see if any have lots of reference UIDs... possibly rtdose or rtstruct would.

**Comment by vsoch** [comment]
okay! Actually I realized after asking I can just look at the script :) My only question is then what example data is best to use? Also, I'm terribly disappointed in my old deid docs - so I'm going to redo them with this example! Will close this issue here --> https://github.com/pydicom/deid/issues/74

**Comment by vsoch** [comment]
hey @scaramallion, @mrbean-bremen,  and @darcymason thanks for your patience! I did a nice revamp of the documentation, and a little refactoring of deid itself so it's a little better organized **and** the user can supply some custom recipe to interact with the dicom. I've created a complete example for you here:

https://pydicom.github.io/deid/examples/func-replace/

(and note that since you have your own data files you can probably just [start with the recipe](https://pydicom.github.io/deid/examples/func-replace/#the-deid-recipe))

And specifically you will want to [install from Github](https://pydicom.github.io/deid/install/local/) because I haven't pushed to pypi yet. I have, however, pushed the docker container for it, so if your preference is docker you can do that too :)

Could you take a look, and let me know if anything needs clarifying, or if you want to suggest changes to the functions?  When you give your blessing I'll release on pypi and share with others too :) Thanks!

**Comment by scaramallion** [comment]
I'll need to check, but I believe FoR UID is study specific, so if the Study UID changes so too should the FoR UID (?).

I was thinking of adding a bit more control, probably `--study` (default) to change all UIDs at  the study level and` --series` to change them at the series level (and leaving the Study and FoR UIDs as is). And given I hit a bug in a third-party app with length 64 UIDs, I'll also add a `--uid-length int` argument for specifying the length of the generated UIDs.

**Comment by vsoch** [comment]
If you care to test with deid, you would just write this custom logic into a function. I'm not sure if you saw my post @scaramallion do you not care to try it?

**Comment by scaramallion** [comment]
@vsoch I'll have a look, but a bit busy at the moment.

**Comment by vsoch** [comment]
Awesome! That's all I wanted to hear, haha. I'm closing up for the day so please take your time! If you review too soon I'll lose self control and have to work on it, and then probably starve because I didn't eat dinner. Have a good rest of your day!

**Comment by mrbean-bremen** [comment]
> I'll need to check, but I believe FoR UID is study specific, so if the Study UID changes so too should the FoR UID 

You are right - I forgot this. I was thinking that it may make sense to leave the FOR if you are going to relate the derived images to the original images (as they have the same coordinate system), but that would not be DICOM-conform and can be achieved in other ways.

**Pull request closed without merging**
