### PR TITLE
Added support for pydicom_PIL.py to run from the command line

### PR DESCRIPTION
**Pull request by bastula**
#### What contibution are you adding? How do we use it?

The pydicom_PIL.py script can now accept command line arguments to display images. Prior to this PR, it would be necessary to import the module from another script.

#### Any other comments?

 - [ ] I have added a single script or subfolder to a topic folder
 - [x] I have added some form of documentation and my contact with the contribution
 - [ ] I have added a link to the contribution in the topic folder's `README.md`

### CODE REVIEW

**Comment by vsoch** [comment]
hey @bastula this is a good idea! The script assumes that the user is (correctly) providing the input as the first argument, but it will spit out an ugly error if the user does not. Would you think it would make sense to do a check for the length of sys.argv, and if missing an input, give the user some usage? And what if the file doesn't exist?

And then in addition, would you mind adding some notes about how to use the executable where a user can find it? Thank you!

**Comment by bastula** [comment]
@vsoch Do you think argparse is overkill for this simple script and just do manual parsing? I'm inclined to use argparse as it takes care of most if not all of the above mentioned issues 😄

**Comment by vsoch** [comment]
Argparse is much better :) It's never overkill to do something the best that you know how. That's called caring.

**Review by vsoch — CHANGES_REQUESTED** [review]
okay, here is my quick review. First let's check for providing an invalid file name:

```bash
$ python pydicom_PIL.py asddferror: asddf is not a valid file.
usage: pydicom_PIL.py [-h] filename

View DICOM images using the Python Image Library.

positional arguments:
  filename    Filename of DICOM image

optional arguments:
  -h, --help  show this help message and exit
```
Good :) Now let's not provide anything.

```bash
$ python pydicom_PIL.py
error: the following arguments are required: filename
usage: pydicom_PIL.py [-h] filename

View DICOM images using the Python Image Library.

positional arguments:
  filename    Filename of DICOM image

optional arguments:
  -h, --help  show this help message and exit
```
Also good!

Now let's provide a relative path:

```bash
$ python pydicom_PIL.py ../../deid/deid/data/dicom-cookies/image1.dcm 
Traceback (most recent call last):
  File "pydicom_PIL.py", line 143, in <module>
    show_PIL(ds)
  File "pydicom_PIL.py", line 114, in show_PIL
    im = get_PIL_image(dataset)
  File "pydicom_PIL.py", line 100, in get_PIL_image
    "raw", mode, 0, 1)
  File "/home/vanessa/anaconda3/lib/python3.6/site-packages/PIL/Image.py", line 2398, in frombuffer
    return frombytes(mode, size, data, decoder_name, args)
  File "/home/vanessa/anaconda3/lib/python3.6/site-packages/PIL/Image.py", line 2331, in frombytes
    im.frombytes(data, decoder_name, args)
  File "/home/vanessa/anaconda3/lib/python3.6/site-packages/PIL/Image.py", line 786, in frombytes
    raise ValueError("not enough image data")
ValueError: not enough image data
```
okay, first request for change! Let's assume that the user / tester does not have some nice dicoms off hand. Could you please add a README.md to the viewers/ folder that includes the example usage (right now in the header of the pydicom_PIL.y file, which is also good). And before you show the "From the command line usage" have a wget to grab some publicly available file? We want to minimize the steps that the user needs to take to get this up and running.

**Comment by bastula** [comment]
Thanks for the feedback.

- Relative path works for me with a valid file. Not sure if there is something wrong with your DICOM file / PIL module?
- There is example data that comes with pydicom (even when installing from pip). We could just point to that, since the user would already have that on disk. Even more so if they are installing from source.
- Alternatively, if you know of good resources for DICOM data we could add them to the readme, since it would apply to all viewers in this folder.

**Comment by vsoch** [comment]
I didn't mean to say that the relative path didn't work (it likely does!) my file was bad, and this prompted me to request that we (as the repo) provide a known working example for the user to take advantage of and download. Yes, I would find a direct link to one of the pydicom files, and show a wget of a single file directly from Github (so they don't need to poke around their computer to find it, even if pydicom is installed somewhere).

**Comment by darcymason** [comment]
Archiving contrib repository, closing issues first...

**Pull request closed without merging**
